### ISSUE TITLE
conda-build API change removed verbose keyword

### ISSUE THREAD

**Issue by TomAugspurger** [pelson/Obvious-CI#55]
I'm seeing

``` pytb
Traceback (most recent call last):
  File "/opt/conda/bin/obvci_conda_build_dir", line 9, in <module>
    load_entry_point('Obvious-ci==0.4.0.dev1', 'console_scripts', 'obvci_conda_build_dir')()
  File "/opt/conda/lib/python3.4/site-packages/obvci/cli/conda_build_dir.py", line 19, in main
    return Builder.handle_args(args).main()
  File "/opt/conda/lib/python3.4/site-packages/obvci/conda_tools/build_directory.py", line 248, in main
    self.build(meta)
  File "/opt/conda/lib/python3.4/site-packages/obvci/conda_tools/build_directory.py", line 226, in build
    build.build(meta.meta)
  File "/opt/conda/lib/python3.4/site-packages/obvci/conda_tools/build.py", line 23, in build
    build_module.build(meta, verbose=False, post=None)

TypeError: build() got an unexpected keyword argument 'verbose' ./scripts/run_docker_build.sh returned exit code 1
```

That's on `conda-build-1.19.0`. I guess the problem is these two lines [here](https://github.com/pelson/Obvious-CI/blob/18c384278ae042e9767eec03982de905779f7211/obvci/conda_tools/build.py#L23)?

**Comment by pelson** [comment]
Thanks @TomAugspurger - yes, should be a simple fix. I've actually been meaning to getting around to deprecating ObviousCI's conda build functionality in favour of conda-build-all - the latter has more testing and a better interface than obvious-ci.

Indeed, this was fixed there in https://github.com/SciTools/conda-build-all/pull/19.

Have you taken a look at conda-build-all, and does it fit the bill for your requirements?
