### ISSUE TITLE
Failed on Start-Process on Appveyor

### ISSUE THREAD

**Issue by snorfalorpagus** [pelson/Obvious-CI#68]
I've been getting the following exception for the past few days when trying to bootstrap miniconda on Appveyor:

https://ci.appveyor.com/project/snorfalorpagus/pywr/build/job/lpkormx8pqeh2rsy

```
appveyor DownloadFile "https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py"
Downloading bootstrap-obvious-ci-and-miniconda.py (4,124 bytes)...100%
python bootstrap-obvious-ci-and-miniconda.py %CONDA_INSTALL_LOCN% %TARGET_ARCH% %CONDA_PY:~0,1% --without-obvci
Start-Process : This command cannot be run due to the error: The file or 
directory is corrupted and unreadable.
At line:1 char:1
+ Start-Process -FilePath Miniconda3-latest-Windows-x86_64.exe -Argumen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp 
   erationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C 
   ommands.StartProcessCommand
 
Downloading from http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
Traceback (most recent call last):
  File "bootstrap-obvious-ci-and-miniconda.py", line 103, in <module>
    install_obvci=not args.without_obvci)
  File "bootstrap-obvious-ci-and-miniconda.py", line 78, in main
    subprocess.check_call(cmd)
  File "C:\Python27\lib\subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['powershell', 'Start-Process', '-FilePath', 'Miniconda3-latest-Windows-x86_64.exe', '-ArgumentList', '/S,/D=C:\\conda', '-Wait']' returned non-zero exit status 1
Command exited with code 1
```

It looks like the dowload is failing for some reason but from the exception I don't know exactly what's gone wrong.

**Comment by ocefpaf** [comment]
See #67 

Meanwhile you can use https://raw.githubusercontent.com/conda-forge/conda-smithy/master/bootstrap-obvious-ci-and-miniconda.py instead.

**Comment by snorfalorpagus** [comment]
Thanks @ocefpaf. That patch seems to work. I searched the issues but didn't think to look at the PRs.

When setting up my own project I found the easiest way to get CI running was to copy some of the conda-forge build scripts, which includes this.

**Comment by takluyver** [comment]
I'm also making this switch for testing Jupyter notebook.
